exports.api = {
    register: `register`,
    categoryList: `category/list`,
    stateList: `state/list`,
    cityList: `cities/list`,
    registerSendOtp: `send-otp`,
    otpVerify: `verify-otp`,
    dashboard: `provider/home`,
    userChatList: `provider/chat/user-list`,
    addNewsletter: `newsletter/add`,
    planList: `admin/plan`,
    profile: `user/profile`,
    deleteAccount: `delete`,
    advertisement: `advertisement/list`,
    deleteAdvertisement: `advertisement/delete/`,
    updateAdvertisement: `advertisement/update/`,
    addAdvertisement: `advertisement/add`,
    advertisementDetail: `advertisement/details/`,
    advertisementChangeStatus: `admin/advertisement/status/`,
    tagsList: `tag/list`,
    networkDirectory: `provider/List`,
}