exports.routes = {
    login: `/sign-in`,
    signup: `/sign-up`,
    providerRegister: `/provider/sign-up`,
    dashboard: `/provider/dashboard`,
    message: `/provider/message`,
    myJobs: `/provider/jobs`,
    jobDetails: `/provider/job/info`,
    careNetwork: `/provider/care-network`,
    advertisement: `/provider/advertisement`,
    networkDirectory: `/provider/network-directory`,
    profile: `/provider/profile`,
    calendar: `/provider/calendar`,
    subscriptionPlan: `/provider/subscription-plan`,
    newsletter: `/provider/newsletter`,
}