exports.routes = {
    login: `/sign-in`,
    signup: `/sign-up`,
    providerRegister: `/provider/sign-up`,
    dashboard: `/provider/dashboard`,
    message: `/provider/message`,
    myJobs: `/provider/jobs`,
    lockedJobs: `/provider/locked/jobs`,
    jobDetails: `/provider/job/info`,
    careNetwork: `/provider/care-network`,
    addPost: `/provider/care-network/job-post`,
    postedJob: `/provider/care-network/posted-job`,
    careNetworkDetails: `/provider/care-network/info`,
    advertisement: `/provider/advertisement`,
    postedAdvertisement: `/provider/advertisement/posted`,
    advertisementDetails: `/provider/advertisement/info`,
    networkDirectory: `/provider/network-directory`,
    profile: `/provider/profile`,
    calendar: `/provider/calendar`,
    subscriptionPlan: `/provider/subscription-plan`,
    newsletter: `/provider/newsletter`,
    aboutUs: `/provider/about-us`,
    privacyPolicy: `/provider/privacy-policy`,
    termsCondition: `/provider/terms-condition`,
}