exports.api = {
    login: `login`,
    sendOtp: `send-otp`,
    registerSendOtp: `register/send-otp`,
    otpVerify: `verify-otp`,
    register: `register`,
    logout: `logout`,
    dashboard: `user/home`,
    providerList: `service/chat/provider-list`,
    providerDetail: `provider/detail/`,
    bookingList: `service/booking/list`,
    myJobs: `service/request/myjob`,
    jobDetail: `service/request-details`,
    profile: `user/profile`,
    updateProfile: `user/update/`,
    updateProfileImage: `user/profile-image`,
    deleteAccount: `delete`,
    careNetworkList: `admin/posted/job-list`,
    planList: `admin/plan`,
}