exports.api = {
    login: `login`,
    sendOtp: `send-otp`,
    registerSendOtp: `register/send-otp`,
    otpVerify: `verify-otp`,
    register: `register`,
    logout: `logout`,
    dashboard: `user/home`,
    providerList: `service/chat/provider-list`,
    providerDetail: `provider/detail/`,
    bookingList: `service/booking/list`,
    myJobs: `service/request/myjob`,
    jobDetail: `service/request-details`,
    profile: `user/profile`,
    updateProfile: `user/update/`,
}