exports.routes = {
    home: `/`,
    login: `/user/sign-in`,
    register: `/user/sign-up`,
    otp: `/user/verification-otp`,
    dashboard: `/user/dashboard`,
    message: `/user/message`,
    myJobs: `/user/jobs`,
    jobDetails: `/user/job/info`,
    careNetwork: `/user/care-network`,
    careNetworkDetails: `/user/care-network/info`,
    jobRequest: `/user/care-network/job-request`,
    appliedJob: `/user/care-network/applied-job`,
    postedJob: `/user/care-network/posted-job`,
    addPost: `/user/care-network/job-post`,
    profile: `/user/profile`,
    calendar: `/user/calendar`,
    subscriptionPlan: `/user/subscription-plan`,
    newsletter: `/user/newsletter`,
}